//
// Created by Jimmy on 03.06.2022.
//

#ifndef PROJECT_PASSWORD_MANAGER_ADDCATEGORY_H
#define PROJECT_PASSWORD_MANAGER_ADDCATEGORY_H


class addCategory {

};


#endif //PROJECT_PASSWORD_MANAGER_ADDCATEGORY_H
