//
// Created by Jimmy on 03.06.2022.
//

#ifndef PROJECT_PASSWORD_MANAGER_DELETECATEGORY_H
#define PROJECT_PASSWORD_MANAGER_DELETECATEGORY_H


class deleteCategory {

};


#endif //PROJECT_PASSWORD_MANAGER_DELETECATEGORY_H
