//
// Created by Jimmy on 03.06.2022.
//

#ifndef PROJECT_PASSWORD_MANAGER_DELETEPASSWORD_H
#define PROJECT_PASSWORD_MANAGER_DELETEPASSWORD_H


struct deletePassword {

};


#endif //PROJECT_PASSWORD_MANAGER_DELETEPASSWORD_H
